apiVersion: v3
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: argolab
    repository: oci://ghcr.io/noamkazum/helm
    version: 1.0.1
    alias: deploy1
  - name: argolab
    repository: oci://ghcr.io/noamkazum/helm
    version: 1.0.1
    alias: deploy2
version: 1.0.0
appVersion: "1.0.0"